name: hosan_notice
description: A notification app for Hosan High School.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.1+36

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  google_sign_in: ^5.1.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.19
  firebase_analytics: ^9.0.5
  firebase_remote_config: ^2.0.8
  flutter_local_notifications: ^9.0.0
  package_info: ^2.0.2
  url_launcher: ^6.0.11
  cloud_firestore: ^3.1.6
  webview_flutter: ^3.0.0
  double_back_to_close: ^2.0.0
  intl: ^0.17.0
  table_calendar: ^3.0.2
  http: ^0.13.4
  android_intent_plus: ^3.1.1
  permission_handler: ^9.2.0
  workmanager: ^0.5.0
  flutter_foreground_task: ^3.2.0
  device_info_plus: ^3.2.1
  localstorage: ^4.0.0+1
  fluttertoast: ^8.0.8
  firebase_messaging: ^11.4.1
  home_widget: ^0.1.5
  flutter_blue: ^0.8.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.5
  pigeon: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Black.otf
          weight: 900
        - asset: fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: fonts/Pretendard-Bold.otf
          weight: 700
        - asset: fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: fonts/Pretendard-Medium.otf
          weight: 500
        - asset: fonts/Pretendard-Regular.otf
          weight: 400
        - asset: fonts/Pretendard-Light.otf
          weight: 300
        - asset: fonts/Pretendard-Light.otf
          weight: 200
        - asset: fonts/Pretendard-Thin.otf
          weight: 100

flutter_native_splash:
  color: "#EDE7F6"
  image: "assets/hosan.png"